version: 2

release:
  github:
    owner: qownnotes
    name: qc
  name_template: "{{.Tag}}"
# https://goreleaser.com/customization/homebrew/
#brews:
#  -
#    tap:
#      owner: qownnotes
#      name: homebrew-qc
#    description: "QOwnNotes command-line snippet manager"
#    homepage: "https://github.com/qownnotes/qc"
#    dependencies:
#      - fzf
#    install: |
#      bin.install Dir['qc']
#      zsh_completion.install "misc/completions/zsh/_qc"
#    test: |
#      system "#{bin}/qc"
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
    main: .
    ldflags: -s -w -X github.com/qownnotes/qc/cmd.version={{.Version}}
archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template:
      "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
      .Arm }}{{ end }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - misc/completions/zsh/_qc
nfpms:
  - homepage: https://github.com/qownnotes/qc
    maintainer: Patrizio Bekerle <patrizio@bekerle.com>
    description: "QOwnNotes command-line snippet manager"
    bindir: /usr/local/bin
    license: MIT
    formats:
      - deb
      - rpm
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
