name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "doc/**"
      - "LICENSE"
      - "justfile"
  pull_request:
env:
  GO_VERSION: "1.22"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build the code
        run: go build -o qc main.go

      - name: Run unit tests
        run: go test ./...
